version: '3.8'

services:
  # PostgreSQL Database Service
  database:
    image: postgres:16-alpine
    container_name: coaching_flow_db
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: coaching_flow_db
      POSTGRES_USER: coaching_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-coaching_secure_password_2024}
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    volumes:
      # Data persistence
      - postgres_data:/var/lib/postgresql/data
      # Optional: Custom initialization scripts
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - coaching_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U coaching_user -d coaching_flow_db']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

# Named volumes for data persistence
volumes:
  postgres_data:
    name: coaching_flow_postgres_data

# Custom network for service communication
networks:
  coaching_network:
    name: coaching_flow_network
    driver: bridge
